### PR TITLE
FIX DatabaseStore binary safety (minor)

### PR DESCRIPTION
**Pull request by dnsl48**
This PR is a follow up on the #49 for the next minor release (hybridsessions 2.2)

### CODE REVIEW

**Comment by robbieaverill** [comment]
Nice one! A couple of quick things, PSR-2 linting and method naming should be camelCase

**Comment by dnsl48** [comment]
oh, that's interesting. our phpcs with our settings doesn't seem to be catching snake case methods

**Comment by robbieaverill** [comment]
Oh yeah, the framework ruleset is particularly liberal 😆 

We should be aiming for PSR-12 with no exclusions wherever possible, but some SilverStripe practices require us to deviate... by the way, I'll update the phpcs ruleset in this module separately so don't worry about that for now.

**Comment by dnsl48** [comment]
I'll be waiting for #52 to get merged, then I'll rebase this one on top of it. Otherwise there'll be a conflict.

**Comment by robbieaverill** [comment]
I've tagged your last patch as 2.1.2 and merged up the branches

**Comment by dnsl48** [comment]
ok thanks. ready for a review

**Comment by dnsl48** [comment]
done

**Pull request merged**
